version: '3.5'

services:
  orthanc:
    image: jodogne/orthanc-plugins:1.5.6
    hostname: orthanc
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    restart: unless-stopped
  web:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
