version: '3.5'

services:
  orthanc:
    image: jodogne/orthanc-plugins:1.5.7
    hostname: orthanc
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    restart: unless-stopped
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80' #ngnix proxy
    depends_on:
      - orthanc
