version: 0.2

# env:
#   variables:
#     BUILD_ENV: "staging|preprod|production"
#     S3_BUCKET: ""
#     CLOUDFRONT_DISTRIB: ""

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            # Get latest revision
            - git checkout $(aws ssm get-parameter --name /${PROJECT}/${ENVIRONMENT}/cicd/${APP}/revision | jq -r .Parameter.Value)
            # Install node dependancies.
            #- npm config set @rofim:registry https://npm.pkg.github.com
            #- npm config set //npm.pkg.github.com/:_authToken=${GITHUB_NPM_PASSWORD}
            #- npm ci
            - yarn install
    build:
        commands:
            # Builds Angular application. You can also build using custom environment here like mock or staging
            - echo Build started on `date`
            - sed -i "s/ORTHANC_DOMAIN_NAME/$ORTHANC_DOMAIN_NAME/" platform/app/.env.rofim.example
            - cp -f platform/app/.env.rofim.example platform/app/.env
            - yarn build
            - echo Build completed on `date`
    post_build:
        commands:
            - echo Deployment started on `date`
            # Copy dist folder to S3 bucket, As of Angular 6, builds are stored inside an app folder in distribution and not at the root of the dist folder
            - aws s3 sync platform/app/dist/ s3://${S3_BUCKET}/ --delete
            # Invalidate files on CloudFront
            - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIB} --paths '/*'
            - echo Deployment completed on `date`
