# Stage 2: Bundle the built application into a Docker container
FROM nginx:stable-alpine
ENV PORT=80
ENV APP_GCP_URL=''

# Copy the built application
RUN rm /etc/nginx/conf.d/default.conf
COPY .docker/Viewer-v3.x /etc/nginx/conf.d
COPY .docker/Viewer-v3.x /usr/src
COPY  ./platform/viewer/dist /usr/share/nginx/html

# Copy the entrypoint script
RUN chmod -R 777 /usr/share/nginx/html/
RUN chmod -R 777 /usr/src/

# Start the application
ENTRYPOINT ["/usr/src/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
