version: '3.6'
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  orthanc:
    image: jodogne/orthanc-plugins:latest
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - orthanc-data:/var/lib/orthanc/db/

  viewer:
    image: ohif/viewer:latest
    ports:
      - "3000:3000"
    links:
      - mongo
      - orthanc
      - "orthanc:pacsIP"
      - "orthanc:pacsip"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ohif
    volumes:
      - ./dockersupport/app.json:/app/app.json

volumes:
  orthanc-data: