# Stage 1: Build the app
FROM node:16-slim as builder
RUN mkdir /app
WORKDIR /app

COPY ["package.json", "yarn.lock", "preinstall.js", "./"]
COPY extensions /app/extensions
COPY modes /app/modes
COPY platform /app/platform

# Run the install before copying the rest of the files
RUN yarn install --frozen-lockfile --verbose

COPY . .

RUN yarn run build

# Remove dev dependencies
RUN yarn install --production=true

# Stage 2: Bundle the built application into a Docker container
FROM node:16-slim
WORKDIR /app
ENV PORT=3000
ENV APP_GCP_URL=''

# Copy files from the build stage
COPY .docker/Viewer-v3.x/entrypoint.sh /app/entrypoint.sh
COPY --from=builder /app/platform/viewer/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/platform/viewer/server.js /app/server.js

# Start the app
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["node", "/app/server.js"]
