# Stage 1: Build the application
FROM node:16-slim as builder
RUN mkdir /app
WORKDIR /app

# Copy files
COPY ["package.json", "yarn.lock", "preinstall.js", "./"]
COPY extensions /app/extensions
COPY modes /app/modes
COPY platform /app/platform

# Run the install before copying the rest of the files
RUN yarn config set workspaces-experimental true
RUN yarn install --frozen-lockfile --verbose

COPY . .

RUN yarn run build

# Stage 2: Bundle the built application into a Docker container
FROM nginx:stable-alpine
ENV PORT=80
ENV APP_GCP_URL=''

# Copy the built application
RUN rm /etc/nginx/conf.d/default.conf
COPY .docker/Viewer-v3.x /etc/nginx/conf.d
COPY .docker/Viewer-v3.x /usr/src
COPY --from=builder /app/platform/viewer/dist /usr/share/nginx/html

# Copy the entrypoint script
RUN chmod -R 777 /usr/share/nginx/html/
RUN chmod -R 777 /usr/src/

# Start the application
ENTRYPOINT ["/usr/src/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
