# Use Nginx Alpine image
FROM nginx:stable-alpine
RUN apk add bash

## Copy Nginx configuration
RUN rm -rf /etc/nginx/conf.d
COPY .docker/Viewer-v2.x /etc/nginx/conf.d
COPY .docker/Viewer-v2.x/entrypoint.sh /
COPY ./platform/viewer/dist /usr/share/nginx/html

## Expose Port 80
EXPOSE 80

## Change entrypoint permissions and run
RUN chmod 777 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]


#### Build and Push Docker Image
# export PUBLIC_URL=./ && yarn build && docker build -f Dockerfile-Local-Build -t oitrepo.ccr.cancer.gov/mibair/ohif_viewer . && docker push oitrepo.ccr.cancer.gov/mibair/ohif_viewer:latest
