# Stage 1: Build the application
FROM node:18-slim as builder
RUN mkdir /app
WORKDIR /app

# Copy files
COPY ["package.json", "yarn.lock", "preinstall.js", "./"]
COPY extensions /app/extensions
COPY modes /app/modes
COPY platform /app/platform

# Run the install before copying the rest of the files
RUN yarn config set workspaces-experimental true
RUN yarn install --frozen-lockfile --verbose

COPY . .

RUN yarn run build:dev

# Stage 2: Bundle the built application into a Docker container
FROM nginx:stable-alpine
ENV PORT=80
WORKDIR /app
ENV APP_GCP_URL=''
ENV APP_URL_PREFIX='airstudies-dev'

# Update packages
RUN apk -U upgrade --no-cache

# Update the package list and install dependencies
RUN apk add --no-cache python3 py3-pip curl bash aws-cli

# Check AWS CLI version
RUN aws --version

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy the built application
RUN rm /etc/nginx/conf.d/default.conf
COPY .docker/Viewer-v3.x/default.conf /etc/nginx/conf.d
COPY .docker/Viewer-v3.x /app
COPY --from=builder /app/platform/viewer/dist /usr/share/nginx/html

# Copy the entrypoint script
RUN chmod -R 777 /usr/share/nginx/html/
RUN chmod -R 777 /app/

# Start the application
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]


# Use the following command to build the image in macOS
#docker build --platform linux/amd64 -f Dockerfile-MIB-AIR -t viewer-test:latest .
