# Stage 1: Build the application
FROM node:20-slim as builder

# Setup the working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
RUN apt-get update && apt-get install -y build-essential python3

COPY ./ /usr/src/app/

# Install bun and lerna (required by build scripts)
RUN npm install -g bun@1.2.23
RUN npm install -g lerna@7.4.2
ENV PATH=/usr/local/bin:/usr/src/app/node_modules/.bin:$PATH

# Install node dependencies
RUN yarn config set workspaces-experimental true
RUN bun install

# set APP_CONFIG for dcm4chee
ENV APP_CONFIG=config/docker-nginx-dcm4chee.js

# Build the application
RUN bun run build

# Stage 2: Bundle the built application into a Docker container which runs NGINX using Alpine Linux
FROM nginx:alpine

RUN mkdir -p /var/log/nginx /var/www/html

COPY --from=builder /usr/src/app/platform/app/dist /var/www/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
