/**
 * I18N-04 — blackvoxel-ai i18next resource bundle.
 *
 * Registers an 'blackvoxel-ai' namespace with `en` + `pt-BR` keys for the
 * extension's primary user-facing strings (panel header, section headers,
 * buttons, disclaimers, the mode gate, and the DICOM import affordance).
 *
 * The bundle is added to the shared @ohif/i18n singleton at extension load so
 * t('blackvoxel-ai:key') resolves the moment a component renders. addResource-
 * Bundle is idempotent here (we pass deep=true, overwrite=true).
 *
 * NOTE on locale codes: OHIF uses 'en-US' / 'pt-BR'. i18next resolves 'en-US'
 * to the 'en' bundle via language fallback (en-US -> en), so we register the
 * English bundle under 'en' and the Portuguese bundle under 'pt-BR'. We also
 * register the Portuguese bundle under bare 'pt' for safety.
 */

import i18n from '@ohif/i18n';

export const BV_AI_NS = 'blackvoxel-ai';

// OHIF canonical locale codes the LanguageToggle switches between. OHIF/platform
// i18n uses 'en-US' / 'pt-BR' (see platform/i18n/src/index.js). 'en-US' resolves
// to our 'en' bundle via i18next language fallback (en-US -> en).
export const OHIF_LOCALE_EN = 'en-US';
export const OHIF_LOCALE_PT = 'pt-BR';

const en = {
  // Panel header
  'panel.title': 'BlackVoxel AI — Findings',
  'panel.badge.mock': 'Mock',
  'panel.badge.research': 'Research',
  'panel.badge.experimental': 'Experimental',

  // States
  'state.analyzing': 'Analyzing…',
  'state.sessionExpired': 'Session expired. Redirecting to login…',
  'state.noFindings': 'No findings detected.',
  'state.noProbableOrUncertain': 'No probable or uncertain findings.',
  'state.offlineBanner': 'Offline results — showing demonstration data',

  // Findings section
  'findings.header': 'FINDINGS ({{count}})',
  'findings.headerBands': 'FINDINGS — {{count}} probable',
  'findings.processedIn': 'Processed in {{seconds}}s',
  'findings.group.probable': 'PROBABLE ({{count}})',
  'findings.group.uncertain': 'UNCERTAIN ({{count}})',
  'findings.unlikelyToggle': '{{count}} unlikely findings',
  'findings.noLocalization': 'Localization not available in this model version',
  // CXR-32: anatomy grounding (proxy-seg-v1) — explanatory location, not a diagnosis.
  'findings.lat.right': 'right lung',
  'findings.lat.left': 'left lung',
  'findings.zone.upper': 'upper zone',
  'findings.zone.mid': 'mid zone',
  'findings.zone.lower': 'lower zone',
  'findings.location': '{{zone}}, {{lat}}',
  'findings.locationZoneOnly': '{{zone}}',
  'findings.locationLatOnly': '{{lat}}',

  // Report draft
  'report.title': 'Report Draft',
  'report.beta': 'Beta',
  'report.section.technique': 'TECHNIQUE',
  'report.section.findings': 'FINDINGS',
  'report.section.impression': 'IMPRESSION',
  'report.copy': 'Copy Draft',
  'report.copied': 'Copied!',
  'report.disclaimer':
    'This draft was generated by AI and requires review and sign-off by a licensed physician before any clinical use.',
  'report.source.medgemma': 'Draft generated by AI (MedGemma)',
  'report.source.free': 'Draft: free model (deterministic template)',
  'report.paidUnavailable': 'paid model unavailable',
  'report.inconsistent': '⚠ Draft inconsistent with findings — review:',
  'report.consistent': '✓ Draft consistent with the model findings',

  // Report draft — measurements subsection (MIMPS-30)
  'report.section.medicoes': 'MEASUREMENTS',

  // Measurements section (MIMPS-29)
  'measurement.section.title': 'MEASUREMENTS ({{count}})',
  'measurement.suggestion': 'AI suggestion: {{label}}',
  'measurement.noSuggestion': 'Could not identify the structure',
  'measurement.overrideLabel': 'Structure',
  'measurement.overrideOther': 'Other…',
  'measurement.overrideFreePlaceholder': 'Type a structure',
  'measurement.uncalibrated': 'not calibrated',
  'measurement.confirm': 'Confirm',
  'measurement.confirmed': 'Confirmed',
  'measurement.unconfirm': 'Edit',
  'measurement.ict': 'CTR {{value}}',
  'measurement.ictNote': 'measurement, not a diagnosis',
  'measurement.measurementNotDiagnosis': 'measurement, not a diagnosis',
  'measurement.abstain': 'Could not identify the structure.',
  'measurement.empty': 'Draw a ruler to measure a structure.',

  // Server disclaimer fallback
  'disclaimer.research': 'For research use only. Not a substitute for a physician’s report.',

  // Non-research placeholder
  'placeholder.aiResearchOnly': 'AI models are available in Research mode only.',

  // Viewer mode gate
  'mode.brand': 'BlackVoxel MIMPS',
  'mode.researchOnlyBadge': 'Research Only',
  'mode.prompt': 'Select the viewer usage mode to continue.',
  'mode.research.title': 'Research',
  'mode.research.desc':
    'For research use only — AI results must not be used for clinical decisions.',
  'mode.clinical.title': 'Clinical',
  'mode.clinical.desc':
    'Clinical workflow with validated reporting — physician sign-off required.',
  'mode.clinical.badge': 'Coming soon',
  'mode.confirm': 'Confirm mode',
  'mode.disclaimer': 'For research use only. Not a substitute for a physician’s report.',
  'mode.change': 'Change mode',

  // Language toggle
  'lang.toggleAria': 'Switch language',

  // MIMPS-35: Patient context panel (Clinical mode only)
  'context.panel.title': 'Clinical Context',
  'context.demographics.title': 'PATIENT',
  'context.demographics.id': 'ID',
  'context.demographics.sex': 'Sex',
  'context.demographics.dob': 'DOB',
  'context.demographics.none': 'No patient demographics available.',
  'context.consent.label': 'I confirm consent to use clinical context for this report',
  'context.consent.required': 'Confirm consent to load the clinical context.',
  'context.ephemeral.banner': 'Data used only for this report and then discarded.',
  'context.fetch.button': 'Load clinical context',
  'context.fetch.loading': 'Loading clinical context…',
  'context.fetch.empty': 'No clinical context available for this study.',
  'context.fetch.error': 'Could not load the clinical context.',
  'context.labs.title': 'LABORATORY',
  'context.history.title': 'HISTORY',
  'context.comorbidities.title': 'COMORBIDITIES',
  'context.medications.title': 'MEDICATIONS',
  'context.disclaimer':
    'For physician reasoning only — not an autonomous diagnosis. Reviewed and signed by the radiologist.',

  // SUS-12: Conduta SUS panel (Clinical mode + signed read only; ships dark)
  'conduta.panel.title': 'SUS Regulation Pathway',
  'conduta.intro':
    'From the signed read, draft a SUS regulation request. The physician signs, the regulator decides.',
  'conduta.placeholder.clinicalOnly': 'SUS regulation is available in Clinical mode only.',
  'conduta.unavailable': 'SUS regulation is unavailable.',
  'conduta.requiresSigned': 'Available after the report is signed',
  'conduta.requiresSignedNote':
    'Sign the report first. A regulation request is never drafted from an unsigned read.',
  // Pathway cards
  'conduta.card.acute.title': 'Acute',
  'conduta.card.acute.desc': 'Urgent/emergency pathway — bed/leito request for a single signed read.',
  'conduta.card.chronic.title': 'Chronic',
  'conduta.card.chronic.desc': 'Elective/specialty pathway — outpatient referral for a single signed read.',
  'conduta.card.triage.title': 'Triage',
  'conduta.card.triage.desc': 'Ranks many reads into a worklist — not a single regulation bundle.',
  'conduta.triageNote': 'Triage ranks a worklist; the regulator decides the order. No request is sent from here.',
  // Actions
  'conduta.generateDraft': 'Generate request draft',
  'conduta.retryDraft': 'Try again',
  'conduta.drafting': 'Generating draft…',
  'conduta.rascunhoBadge': 'draft',
  'conduta.suggestionLabel': 'SUGGESTED PRIORITY',
  // Prioridade 0-3 + cor
  'conduta.priorityChip': 'Priority {{priority}} · {{name}}',
  'conduta.color.vermelho': 'red',
  'conduta.color.amarelo': 'yellow',
  'conduta.color.verde': 'green',
  'conduta.color.azul': 'blue',
  'conduta.ruleId': 'rule: {{id}}',
  'conduta.rationaleLabel': 'RATIONALE (editable)',
  'conduta.justificativaLabel': 'JUSTIFICATION (editable)',
  'conduta.justificativaPlaceholder': 'Clinical justification (pt-BR)…',
  'conduta.decidesNote': 'Suggestion only — the physician/regulator decides.',
  // Submit (separate, explicit, confirmed — never auto-send)
  'conduta.confirmSubmitLabel':
    'I confirm I want to send this request to SUS regulation.',
  'conduta.submit': 'Send to regulation',
  'conduta.submitting': 'Sending…',
  'conduta.submitNote': 'Sending is a separate, explicit action — nothing is sent automatically.',
  'conduta.submitted.accepted': '✓ Request structurally accepted',
  'conduta.submitted.rejected': 'Request not accepted — review the problems below',
  'conduta.submitted.trackingId': 'Tracking: {{id}}',
  'conduta.submitted.mockEnv': 'Mock environment — no real RNDS submission (structural signal only).',
  'conduta.reset': 'New draft',
  // Errors
  'conduta.error.unsigned': 'Cannot draft from an unsigned read — sign the report first.',
  'conduta.error.request': 'Request rejected ({{code}}). Review and try again.',
  'conduta.error.generic': 'Could not reach the SUS regulation service. Try again.',
  'conduta.disclaimer':
    'Decision support only — not a diagnosis or a regulatory decision. The physician signs; the regulator decides. Mock environment, no real RNDS submission.',
};

const ptBR: typeof en = {
  // Panel header
  'panel.title': 'BlackVoxel IA — Achados',
  'panel.badge.mock': 'Mock',
  'panel.badge.research': 'Research',
  'panel.badge.experimental': 'Experimental',

  // States
  'state.analyzing': 'Analisando…',
  'state.sessionExpired': 'Sessão expirada. Redirecionando para o login…',
  'state.noFindings': 'Nenhum achado detectado.',
  'state.noProbableOrUncertain': 'Nenhum achado provável ou indeterminado.',
  'state.offlineBanner': 'Resultados offline — exibindo dados de demonstração',

  // Findings section
  'findings.header': 'ACHADOS ({{count}})',
  'findings.headerBands': 'ACHADOS — {{count}} provável(is)',
  'findings.processedIn': 'Processado em {{seconds}}s',
  'findings.group.probable': 'PROVÁVEIS ({{count}})',
  'findings.group.uncertain': 'INDETERMINADOS ({{count}})',
  'findings.unlikelyToggle': '{{count}} achados improváveis',
  'findings.noLocalization': 'Localização não disponível nesta versão do modelo',
  // CXR-32: fundamentação anatômica (proxy-seg-v1) — localização, não diagnóstico.
  'findings.lat.right': 'à direita',
  'findings.lat.left': 'à esquerda',
  'findings.zone.upper': 'terço superior',
  'findings.zone.mid': 'terço médio',
  'findings.zone.lower': 'terço inferior',
  'findings.location': 'campo pulmonar {{zone}} {{lat}}',
  'findings.locationZoneOnly': 'campo pulmonar {{zone}}',
  'findings.locationLatOnly': 'campo pulmonar {{lat}}',

  // Report draft
  'report.title': 'Rascunho de Laudo',
  'report.beta': 'Beta',
  'report.section.technique': 'TÉCNICA',
  'report.section.findings': 'ACHADOS',
  'report.section.impression': 'IMPRESSÃO',
  'report.copy': 'Copiar Rascunho',
  'report.copied': 'Copiado!',
  'report.disclaimer':
    'Este rascunho foi gerado por IA e requer revisão e assinatura de médico habilitado antes de qualquer uso clínico.',
  'report.source.medgemma': 'Rascunho gerado por IA (MedGemma)',
  'report.source.free': 'Rascunho: modelo gratuito (template determinístico)',
  'report.paidUnavailable': 'modelo pago indisponível',
  'report.inconsistent': '⚠ Rascunho inconsistente com os achados — revisar:',
  'report.consistent': '✓ Rascunho consistente com os achados do modelo',

  // Report draft — measurements subsection (MIMPS-30)
  'report.section.medicoes': 'MEDIÇÕES',

  // Measurements section (MIMPS-29)
  'measurement.section.title': 'MEDIÇÕES ({{count}})',
  'measurement.suggestion': 'Sugestão IA: {{label}}',
  'measurement.noSuggestion': 'Não foi possível identificar a estrutura',
  'measurement.overrideLabel': 'Estrutura',
  'measurement.overrideOther': 'Outro…',
  'measurement.overrideFreePlaceholder': 'Digite uma estrutura',
  'measurement.uncalibrated': 'não calibrado',
  'measurement.confirm': 'Confirmar',
  'measurement.confirmed': 'Confirmado',
  'measurement.unconfirm': 'Editar',
  'measurement.ict': 'ICT {{value}}',
  'measurement.ictNote': 'medição, não diagnóstico',
  'measurement.measurementNotDiagnosis': 'medição, não diagnóstico',
  'measurement.abstain': 'Não foi possível identificar a estrutura.',
  'measurement.empty': 'Desenhe uma régua para medir uma estrutura.',

  // Server disclaimer fallback
  'disclaimer.research': 'Uso restrito a pesquisa. Não substitui laudo médico.',

  // Non-research placeholder
  'placeholder.aiResearchOnly': 'Os modelos de IA estão disponíveis apenas no modo Pesquisa.',

  // Viewer mode gate
  'mode.brand': 'BlackVoxel MIMPS',
  'mode.researchOnlyBadge': 'Research Only',
  'mode.prompt': 'Selecione o modo de uso do visualizador antes de continuar.',
  'mode.research.title': 'Pesquisa',
  'mode.research.desc':
    'Uso exclusivo para pesquisa. Resultados de IA não devem ser usados clinicamente.',
  'mode.clinical.title': 'Clínico',
  'mode.clinical.desc':
    'Fluxo clínico validado com laudo médico habilitado.',
  'mode.clinical.badge': 'Em breve',
  'mode.confirm': 'Confirmar modo',
  'mode.disclaimer': 'Uso restrito a pesquisa. Não substitui laudo médico.',
  'mode.change': 'Trocar modo',

  // Language toggle
  'lang.toggleAria': 'Trocar idioma',

  // MIMPS-35: Patient context panel (Clinical mode only)
  'context.panel.title': 'Contexto Clínico',
  'context.demographics.title': 'PACIENTE',
  'context.demographics.id': 'ID',
  'context.demographics.sex': 'Sexo',
  'context.demographics.dob': 'Nasc.',
  'context.demographics.none': 'Dados demográficos do paciente indisponíveis.',
  'context.consent.label': 'Confirmo o consentimento para usar o contexto clínico neste laudo',
  'context.consent.required': 'Confirme o consentimento para carregar o contexto clínico.',
  'context.ephemeral.banner': 'Dados usados apenas neste laudo e descartados.',
  'context.fetch.button': 'Carregar contexto clínico',
  'context.fetch.loading': 'Carregando contexto clínico…',
  'context.fetch.empty': 'Nenhum contexto clínico disponível para este estudo.',
  'context.fetch.error': 'Não foi possível carregar o contexto clínico.',
  'context.labs.title': 'LABORATÓRIO',
  'context.history.title': 'HISTÓRIA',
  'context.comorbidities.title': 'COMORBIDADES',
  'context.medications.title': 'MEDICAÇÕES',
  'context.disclaimer':
    'Apenas para raciocínio médico — não é um diagnóstico autônomo. Revisado e assinado pelo radiologista.',

  // SUS-12: painel Conduta SUS (modo Clínico + laudo assinado; nasce desligado)
  'conduta.panel.title': 'Conduta SUS',
  'conduta.intro':
    'A partir do laudo assinado, gere um rascunho de solicitação de regulação SUS. O médico assina, o regulador decide.',
  'conduta.placeholder.clinicalOnly': 'A regulação SUS está disponível apenas no modo Clínico.',
  'conduta.unavailable': 'Conduta SUS indisponível.',
  'conduta.requiresSigned': 'Disponível após assinatura do laudo',
  'conduta.requiresSignedNote':
    'Assine o laudo primeiro. Uma solicitação nunca é gerada a partir de um laudo não assinado.',
  // Cartões de via
  'conduta.card.acute.title': 'Aguda',
  'conduta.card.acute.desc': 'Via de urgência/emergência — solicitação de leito para um laudo assinado.',
  'conduta.card.chronic.title': 'Crônica',
  'conduta.card.chronic.desc': 'Via eletiva/especialidade — encaminhamento ambulatorial para um laudo assinado.',
  'conduta.card.triage.title': 'Triagem',
  'conduta.card.triage.desc': 'Ordena vários laudos em uma fila — não é um bundle único de regulação.',
  'conduta.triageNote': 'A triagem ordena uma fila; o regulador decide a ordem. Nenhuma solicitação é enviada daqui.',
  // Ações
  'conduta.generateDraft': 'Gerar rascunho de solicitação',
  'conduta.retryDraft': 'Tentar novamente',
  'conduta.drafting': 'Gerando rascunho…',
  'conduta.rascunhoBadge': 'rascunho',
  'conduta.suggestionLabel': 'PRIORIDADE SUGERIDA',
  // Prioridade 0-3 + cor
  'conduta.priorityChip': 'Prioridade {{priority}} · {{name}}',
  'conduta.color.vermelho': 'vermelho',
  'conduta.color.amarelo': 'amarelo',
  'conduta.color.verde': 'verde',
  'conduta.color.azul': 'azul',
  'conduta.ruleId': 'regra: {{id}}',
  'conduta.rationaleLabel': 'JUSTIFICATIVA DA PRIORIDADE (editável)',
  'conduta.justificativaLabel': 'JUSTIFICATIVA CLÍNICA (editável)',
  'conduta.justificativaPlaceholder': 'Justificativa clínica (pt-BR)…',
  'conduta.decidesNote': 'Apenas sugestão — o médico/regulador decide.',
  // Envio (separado, explícito, confirmado — nunca automático)
  'conduta.confirmSubmitLabel':
    'Confirmo que desejo enviar esta solicitação para a regulação do SUS.',
  'conduta.submit': 'Enviar para regulação',
  'conduta.submitting': 'Enviando…',
  'conduta.submitNote': 'O envio é uma ação separada e explícita — nada é enviado automaticamente.',
  'conduta.submitted.accepted': '✓ Solicitação aceita estruturalmente',
  'conduta.submitted.rejected': 'Solicitação não aceita — verifique os problemas abaixo',
  'conduta.submitted.trackingId': 'Protocolo: {{id}}',
  'conduta.submitted.mockEnv': 'Ambiente mock — sem envio real ao RNDS (apenas sinal estrutural).',
  'conduta.reset': 'Novo rascunho',
  // Erros
  'conduta.error.unsigned': 'Não é possível gerar a partir de um laudo não assinado — assine o laudo primeiro.',
  'conduta.error.request': 'Solicitação rejeitada ({{code}}). Revise e tente novamente.',
  'conduta.error.generic': 'Não foi possível contatar o serviço de regulação SUS. Tente novamente.',
  'conduta.disclaimer':
    'Apoio à decisão apenas — não é diagnóstico nem decisão regulatória. O médico assina; o regulador decide. Ambiente mock, sem envio real ao RNDS.',
};

/**
 * Register the bundle on the shared i18next instance. Idempotent — safe to call
 * more than once. Registered under 'en' (so 'en-US' resolves via fallback),
 * 'pt-BR', and bare 'pt'.
 */
export function registerBlackVoxelAILocales(): void {
  i18n.addResourceBundle('en', BV_AI_NS, en, true, true);
  i18n.addResourceBundle('pt-BR', BV_AI_NS, ptBR, true, true);
  i18n.addResourceBundle('pt', BV_AI_NS, ptBR, true, true);
}
