/**
 * I18N-04 — blackvoxel-ai i18next resource bundle.
 *
 * Registers an 'blackvoxel-ai' namespace with `en` + `pt-BR` keys for the
 * extension's primary user-facing strings (panel header, section headers,
 * buttons, disclaimers, the mode gate, and the DICOM import affordance).
 *
 * The bundle is added to the shared @ohif/i18n singleton at extension load so
 * t('blackvoxel-ai:key') resolves the moment a component renders. addResource-
 * Bundle is idempotent here (we pass deep=true, overwrite=true).
 *
 * NOTE on locale codes: OHIF uses 'en-US' / 'pt-BR'. i18next resolves 'en-US'
 * to the 'en' bundle via language fallback (en-US -> en), so we register the
 * English bundle under 'en' and the Portuguese bundle under 'pt-BR'. We also
 * register the Portuguese bundle under bare 'pt' for safety.
 */

import i18n from '@ohif/i18n';

export const BV_AI_NS = 'blackvoxel-ai';

const en = {
  // Panel header
  'panel.title': 'BlackVoxel AI — Findings',
  'panel.badge.mock': 'Mock',
  'panel.badge.research': 'Research',
  'panel.badge.experimental': 'Experimental',

  // States
  'state.analyzing': 'Analyzing…',
  'state.sessionExpired': 'Session expired. Redirecting to login…',
  'state.noFindings': 'No findings detected.',
  'state.noProbableOrUncertain': 'No probable or uncertain findings.',
  'state.offlineBanner': 'Offline results — showing demonstration data',

  // Findings section
  'findings.header': 'FINDINGS ({{count}})',
  'findings.headerBands': 'FINDINGS — {{count}} probable',
  'findings.processedIn': 'Processed in {{seconds}}s',
  'findings.group.probable': 'PROBABLE ({{count}})',
  'findings.group.uncertain': 'UNCERTAIN ({{count}})',
  'findings.unlikelyToggle': '{{count}} unlikely findings',
  'findings.noLocalization': 'Localization not available in this model version',
  // CXR-32: anatomy grounding (proxy-seg-v1) — explanatory location, not a diagnosis.
  'findings.lat.right': 'right lung',
  'findings.lat.left': 'left lung',
  'findings.zone.upper': 'upper zone',
  'findings.zone.mid': 'mid zone',
  'findings.zone.lower': 'lower zone',
  'findings.location': '{{zone}}, {{lat}}',
  'findings.locationZoneOnly': '{{zone}}',
  'findings.locationLatOnly': '{{lat}}',

  // Report draft
  'report.title': 'Report Draft',
  'report.beta': 'Beta',
  'report.section.technique': 'TECHNIQUE',
  'report.section.findings': 'FINDINGS',
  'report.section.impression': 'IMPRESSION',
  'report.copy': 'Copy Draft',
  'report.copied': 'Copied!',
  'report.disclaimer':
    'This draft was generated by AI and requires review and sign-off by a licensed physician before any clinical use.',
  'report.source.medgemma': 'Draft generated by AI (MedGemma)',
  'report.source.free': 'Draft: free model (deterministic template)',
  'report.paidUnavailable': 'paid model unavailable',
  'report.inconsistent': '⚠ Draft inconsistent with findings — review:',
  'report.consistent': '✓ Draft consistent with the model findings',

  // Report draft — measurements subsection (MIMPS-30)
  'report.section.medicoes': 'MEASUREMENTS',

  // Measurements section (MIMPS-29)
  'measurement.section.title': 'MEASUREMENTS ({{count}})',
  'measurement.suggestion': 'AI suggestion: {{label}}',
  'measurement.noSuggestion': 'Could not identify the structure',
  'measurement.overrideLabel': 'Structure',
  'measurement.overrideOther': 'Other…',
  'measurement.overrideFreePlaceholder': 'Type a structure',
  'measurement.uncalibrated': 'not calibrated',
  'measurement.confirm': 'Confirm',
  'measurement.confirmed': 'Confirmed',
  'measurement.unconfirm': 'Edit',
  'measurement.ict': 'CTR {{value}}',
  'measurement.ictNote': 'measurement, not a diagnosis',
  'measurement.measurementNotDiagnosis': 'measurement, not a diagnosis',
  'measurement.abstain': 'Could not identify the structure.',
  'measurement.empty': 'Draw a ruler to measure a structure.',

  // Server disclaimer fallback
  'disclaimer.research': 'For research use only. Not a substitute for a physician’s report.',

  // Non-research placeholder
  'placeholder.aiResearchOnly': 'AI models are available in Research mode only.',

  // DICOM import button
  'import.button': 'Import DICOM',
  'import.note': 'Files stay in the browser — no server upload.',
  'import.aria': 'Import local DICOM files',
  'import.title': 'Import local DICOM — Research mode only',

  // Viewer mode gate
  'mode.brand': 'BlackVoxel MIMPS',
  'mode.researchOnlyBadge': 'Research Only',
  'mode.prompt': 'Select the viewer usage mode to continue.',
  'mode.research.title': 'Research',
  'mode.research.desc':
    'For research use only — AI results must not be used for clinical decisions.',
  'mode.clinical.title': 'Clinical',
  'mode.clinical.desc':
    'Clinical workflow with validated reporting — physician sign-off required.',
  'mode.clinical.badge': 'Coming soon',
  'mode.confirm': 'Confirm mode',
  'mode.disclaimer': 'For research use only. Not a substitute for a physician’s report.',
  'mode.change': 'Change mode',

  // Language toggle
  'lang.toggleAria': 'Switch language',

  // MIMPS-35: Patient context panel (Clinical mode only)
  'context.panel.title': 'Clinical Context',
  'context.demographics.title': 'PATIENT',
  'context.demographics.id': 'ID',
  'context.demographics.sex': 'Sex',
  'context.demographics.dob': 'DOB',
  'context.demographics.none': 'No patient demographics available.',
  'context.consent.label': 'I confirm consent to use clinical context for this report',
  'context.consent.required': 'Confirm consent to load the clinical context.',
  'context.ephemeral.banner': 'Data used only for this report and then discarded.',
  'context.fetch.button': 'Load clinical context',
  'context.fetch.loading': 'Loading clinical context…',
  'context.fetch.empty': 'No clinical context available for this study.',
  'context.fetch.error': 'Could not load the clinical context.',
  'context.labs.title': 'LABORATORY',
  'context.history.title': 'HISTORY',
  'context.comorbidities.title': 'COMORBIDITIES',
  'context.medications.title': 'MEDICATIONS',
  'context.disclaimer':
    'For physician reasoning only — not an autonomous diagnosis. Reviewed and signed by the radiologist.',
};

const ptBR: typeof en = {
  // Panel header
  'panel.title': 'BlackVoxel IA — Achados',
  'panel.badge.mock': 'Mock',
  'panel.badge.research': 'Research',
  'panel.badge.experimental': 'Experimental',

  // States
  'state.analyzing': 'Analisando…',
  'state.sessionExpired': 'Sessão expirada. Redirecionando para o login…',
  'state.noFindings': 'Nenhum achado detectado.',
  'state.noProbableOrUncertain': 'Nenhum achado provável ou indeterminado.',
  'state.offlineBanner': 'Resultados offline — exibindo dados de demonstração',

  // Findings section
  'findings.header': 'ACHADOS ({{count}})',
  'findings.headerBands': 'ACHADOS — {{count}} provável(is)',
  'findings.processedIn': 'Processado em {{seconds}}s',
  'findings.group.probable': 'PROVÁVEIS ({{count}})',
  'findings.group.uncertain': 'INDETERMINADOS ({{count}})',
  'findings.unlikelyToggle': '{{count}} achados improváveis',
  'findings.noLocalization': 'Localização não disponível nesta versão do modelo',
  // CXR-32: fundamentação anatômica (proxy-seg-v1) — localização, não diagnóstico.
  'findings.lat.right': 'à direita',
  'findings.lat.left': 'à esquerda',
  'findings.zone.upper': 'terço superior',
  'findings.zone.mid': 'terço médio',
  'findings.zone.lower': 'terço inferior',
  'findings.location': 'campo pulmonar {{zone}} {{lat}}',
  'findings.locationZoneOnly': 'campo pulmonar {{zone}}',
  'findings.locationLatOnly': 'campo pulmonar {{lat}}',

  // Report draft
  'report.title': 'Rascunho de Laudo',
  'report.beta': 'Beta',
  'report.section.technique': 'TÉCNICA',
  'report.section.findings': 'ACHADOS',
  'report.section.impression': 'IMPRESSÃO',
  'report.copy': 'Copiar Rascunho',
  'report.copied': 'Copiado!',
  'report.disclaimer':
    'Este rascunho foi gerado por IA e requer revisão e assinatura de médico habilitado antes de qualquer uso clínico.',
  'report.source.medgemma': 'Rascunho gerado por IA (MedGemma)',
  'report.source.free': 'Rascunho: modelo gratuito (template determinístico)',
  'report.paidUnavailable': 'modelo pago indisponível',
  'report.inconsistent': '⚠ Rascunho inconsistente com os achados — revisar:',
  'report.consistent': '✓ Rascunho consistente com os achados do modelo',

  // Report draft — measurements subsection (MIMPS-30)
  'report.section.medicoes': 'MEDIÇÕES',

  // Measurements section (MIMPS-29)
  'measurement.section.title': 'MEDIÇÕES ({{count}})',
  'measurement.suggestion': 'Sugestão IA: {{label}}',
  'measurement.noSuggestion': 'Não foi possível identificar a estrutura',
  'measurement.overrideLabel': 'Estrutura',
  'measurement.overrideOther': 'Outro…',
  'measurement.overrideFreePlaceholder': 'Digite uma estrutura',
  'measurement.uncalibrated': 'não calibrado',
  'measurement.confirm': 'Confirmar',
  'measurement.confirmed': 'Confirmado',
  'measurement.unconfirm': 'Editar',
  'measurement.ict': 'ICT {{value}}',
  'measurement.ictNote': 'medição, não diagnóstico',
  'measurement.measurementNotDiagnosis': 'medição, não diagnóstico',
  'measurement.abstain': 'Não foi possível identificar a estrutura.',
  'measurement.empty': 'Desenhe uma régua para medir uma estrutura.',

  // Server disclaimer fallback
  'disclaimer.research': 'Uso restrito a pesquisa. Não substitui laudo médico.',

  // Non-research placeholder
  'placeholder.aiResearchOnly': 'Os modelos de IA estão disponíveis apenas no modo Pesquisa.',

  // DICOM import button
  'import.button': 'Importar DICOM',
  'import.note': 'Arquivos ficam no navegador — nenhum upload para servidor.',
  'import.aria': 'Importar arquivos DICOM locais',
  'import.title': 'Importar DICOM local — apenas modo Pesquisa',

  // Viewer mode gate
  'mode.brand': 'BlackVoxel MIMPS',
  'mode.researchOnlyBadge': 'Research Only',
  'mode.prompt': 'Selecione o modo de uso do visualizador antes de continuar.',
  'mode.research.title': 'Pesquisa',
  'mode.research.desc':
    'Uso exclusivo para pesquisa. Resultados de IA não devem ser usados clinicamente.',
  'mode.clinical.title': 'Clínico',
  'mode.clinical.desc':
    'Fluxo clínico validado com laudo médico habilitado.',
  'mode.clinical.badge': 'Em breve',
  'mode.confirm': 'Confirmar modo',
  'mode.disclaimer': 'Uso restrito a pesquisa. Não substitui laudo médico.',
  'mode.change': 'Trocar modo',

  // Language toggle
  'lang.toggleAria': 'Trocar idioma',

  // MIMPS-35: Patient context panel (Clinical mode only)
  'context.panel.title': 'Contexto Clínico',
  'context.demographics.title': 'PACIENTE',
  'context.demographics.id': 'ID',
  'context.demographics.sex': 'Sexo',
  'context.demographics.dob': 'Nasc.',
  'context.demographics.none': 'Dados demográficos do paciente indisponíveis.',
  'context.consent.label': 'Confirmo o consentimento para usar o contexto clínico neste laudo',
  'context.consent.required': 'Confirme o consentimento para carregar o contexto clínico.',
  'context.ephemeral.banner': 'Dados usados apenas neste laudo e descartados.',
  'context.fetch.button': 'Carregar contexto clínico',
  'context.fetch.loading': 'Carregando contexto clínico…',
  'context.fetch.empty': 'Nenhum contexto clínico disponível para este estudo.',
  'context.fetch.error': 'Não foi possível carregar o contexto clínico.',
  'context.labs.title': 'LABORATÓRIO',
  'context.history.title': 'HISTÓRIA',
  'context.comorbidities.title': 'COMORBIDADES',
  'context.medications.title': 'MEDICAÇÕES',
  'context.disclaimer':
    'Apenas para raciocínio médico — não é um diagnóstico autônomo. Revisado e assinado pelo radiologista.',
};

/**
 * Register the bundle on the shared i18next instance. Idempotent — safe to call
 * more than once. Registered under 'en' (so 'en-US' resolves via fallback),
 * 'pt-BR', and bare 'pt'.
 */
export function registerBlackVoxelAILocales(): void {
  i18n.addResourceBundle('en', BV_AI_NS, en, true, true);
  i18n.addResourceBundle('pt-BR', BV_AI_NS, ptBR, true, true);
  i18n.addResourceBundle('pt', BV_AI_NS, ptBR, true, true);
}
