/**
 * VIEWPORT
 */
export const CLEAR_VIEWPORT = 'VIEWPORT::CLEAR';
export const SET_VIEWPORT_ACTIVE = 'VIEWPORT::SET_ACTIVE';
export const SET_VIEWPORT_LAYOUT = 'VIEWPORT::SET_LAYOUT';
export const UPDATE_VIEWPORT = 'VIEWPORT::UPDATE';
export const SET_VIEWPORT_LAYOUT_AND_VIEWPORT_PANES =
  'VIEWPORT::SET_LAYOUT_AND_PANES';

/**
 * SERVERS
 */
export const ADD_SERVER = 'ADD_SERVER';
export const SET_SERVERS = 'SET_SERVERS';

/**
 * EXTENSIONS
 */
export const SET_EXTENSION_DATA = 'SET_EXTENSION_DATA';
